shell:
  paths:
    - path: /usr/local/bin
    - path: .local/bin
      relative: true
    - path: .local/share/aquaproj-aqua/bin
      relative: true
    - path: /Applications/Sublime Text.app/Contents/SharedSupport/bin
      os: darwin

  env:
    AQUA_POLICY_CONFIG: .aqua/aqua-policy.yaml
    EDITOR: micro
    FZF_DEFAULT_COMMAND: fd --type file --color=always
    FZF_CTRL_T_COMMAND: $FZF_DEFAULT_COMMAND
    GIT_PAGER:
      value: delta
      check: delta
      fallback: less

  aliases:
    cat: bat --paging=never
    k9s-kflow: aws-vault exec admin-kflow -- k9s
    ll: eza -la
    ls: eza
    gs: git status
    lg: lazygit
    nano: micro
    s: kitten ssh
    tre: tre -a
    wtc: wt switch --create
    wts: wt switch
    wtl: wt list
    y: yazi

  functions:
    cdg:
      description: cd to git root
      nu: cd (git rev-parse --show-toplevel)
      zsh: cd "$(git rev-parse --show-toplevel)"
    dff:
      description: diff current branch against base (auto-detects default branch), or --local for uncommitted changes
      nu: git diff $"($in | default main)...HEAD" | diffnav
      zsh: |
        if [[ "$1" == "--local" || "$1" == "-l" ]]; then
            git diff HEAD | diffnav
        else
            local base="${1:-$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')}"
            git diff "${base:-main}...HEAD" | diffnav
        fi
    paws:
      description: print AWS env vars
      nu: $env | transpose key value | where key =~ "AWS" | format pattern '{key}={value}' | to text
      zsh: env | grep AWS
