shell:
  paths:
    - path: /usr/local/bin
    - path: .local/bin
      relative: true
    - path: .local/share/aquaproj-aqua/bin
      relative: true
    - path: /Applications/Sublime Text.app/Contents/SharedSupport/bin
      os: darwin

  env:
    AQUA_POLICY_CONFIG: .aqua/aqua-policy.yaml
    EDITOR: micro
    FZF_DEFAULT_COMMAND: fd --type file --color=always
    FZF_DEFAULT_OPTS: --ansi
    FZF_CTRL_T_COMMAND: $FZF_DEFAULT_COMMAND
    FZF_ALT_C_COMMAND: fd --type d --color=always
    GIT_PAGER:
      value: delta
      check: delta
      fallback: less

  aliases:
    cat: bat
    k9s-kflow: aws-vault exec admin-kflow -- k9s
    ll: eza -la
    ls: eza
    gaa: git add -A
    gc: git commit
    gd: git diff
    gs: git status
    gg: lazygit
    nano: micro
    s: kitten ssh
    tre: eza --tree -a --git-ignore
    wtc: wt switch --create
    wts: wt switch
    wtl: wt list
    wtm: wts ^
    y: yazi

  functions:
    cdg:
      description: cd to git root
      nu: cd (git rev-parse --show-toplevel)
      zsh: cd "$(git rev-parse --show-toplevel)"
    dfg:
      description: diff current branch against base (auto-detects default branch), or --local for uncommitted changes
      nu: git diff $"($in | default main)...HEAD" | diffnav
      zsh: |
        if [[ "$1" == "--local" || "$1" == "-l" ]]; then
            git diff HEAD | diffnav
        else
            local base="${1:-$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')}"
            git diff "${base:-main}...HEAD" | diffnav
        fi
    dff:
      description: "interactive diff browser with fzf + delta (usage: gdd [ref], default main)"
      nu: "echo 'gdd is not supported in nushell'"
      zsh: |
        local base="${1:-$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')}"
        base="${base:-main}"
        git diff --name-only "${base}...HEAD" | \
            fzf --ansi --preview "git diff ${base}...HEAD -- {} | delta" \
                --preview-window=right:70% \
                --bind 'enter:execute(git diff '"${base}"'...HEAD -- {} | delta | less -R)'
    init-plans:
      description: "symlink docs/plans to ../plans/<repo> for the current repo"
      nu: "echo 'init-plans is not supported in nushell'"
      zsh: |
        local root="$(git rev-parse --show-toplevel)"
        local repo="$(basename "$root")"
        local plans_dir="$root/../plans/$repo"
        mkdir -p "$plans_dir" "$root/docs"
        ln -sf "$plans_dir" "$root/docs/plans"
        echo "docs/plans -> $plans_dir"
    paws:
      description: print AWS env vars
      nu: $env | transpose key value | where key =~ "AWS" | format pattern '{key}={value}' | to text
      zsh: env | grep AWS
