new_tab chezmoi
layout splits
cd /Users/mk/.local/share/chezmoi
launch --var window=left zsh -l
launch --location=vsplit zsh -l -c 'lazygit; exec zsh -l'
launch --location=hsplit zsh -l
focus_matching_window var:window=left

new_tab hodgepodge
layout splits
cd /Users/mk/mkramers/hodgepodge
launch --var window=left zsh -l
launch --location=vsplit zsh -l -c 'lazygit; exec zsh -l'
launch --location=hsplit zsh -l
focus_matching_window var:window=left

