new_tab chezmoi
layout splits
cd /Users/mk/.local/share/chezmoi
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab skills
layout splits
cd /Users/mk/altis/skills
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab ml-serve
layout splits
cd /Users/mk/altis/ml-serve
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab nota
layout splits
cd /Users/mk/altis/nota
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab altis-labs-ml-ops
layout splits
cd /Users/mk/altis/altis-labs-ml-ops
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab team
layout splits
cd /Users/mk/altis/team
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab nifti-viewer
layout splits
cd /Users/mk/altis/nifti-viewer
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab cupcake
layout splits
cd /Users/mk/altis/cupcake
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab diffnav
layout splits
cd /Users/mk/mkramers/diffnav
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab security-alerts
layout splits
cd /Users/mk/altis/security-alerts
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab dicom-crawler
layout splits
cd /Users/mk/altis/dicom-crawler
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab compliance
layout splits
cd /Users/mk/altis/compliance
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l

new_tab hodgepodge
layout splits
cd /Users/mk/mkramers/hodgepodge
launch zsh -l
launch --location=vsplit zsh -c 'source ~/.zprofile; gg'
launch --location=hsplit zsh -l
