new_tab chezmoi
layout splits
cd /Users/mk/.local/share/chezmoi
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab skills
layout splits
cd /Users/mk/altis/skills
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab ml-serve
layout splits
cd /Users/mk/altis/ml-serve
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab nota
layout splits
cd /Users/mk/altis/nota
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab altis-labs-ml-ops
layout splits
cd /Users/mk/altis/altis-labs-ml-ops
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab team
layout splits
cd /Users/mk/altis/team
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab nifti-viewer
layout splits
cd /Users/mk/altis/nifti-viewer
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab cupcake
layout splits
cd /Users/mk/altis/cupcake
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab diffnav
layout splits
cd /Users/mk/mkramers/diffnav
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab security-alerts
layout splits
cd /Users/mk/altis/security-alerts
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab dicom-crawler
layout splits
cd /Users/mk/altis/dicom-crawler
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab compliance
layout splits
cd /Users/mk/altis/compliance
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left

new_tab hodgepodge
layout splits
cd /Users/mk/mkramers/hodgepodge
launch --var window=left zsh -l -c 'tmux new-session'
launch --location=vsplit zsh -l -c 'lazygit'
launch --location=hsplit zsh -l -c 'tmux new-session'
focus_matching_window var:window=left
