git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  showFileTree: true
  showRandomTip: false
  nerdFontsVersion: "3"
customCommands:
  - key: 'W'
    description: 'Create worktree'
    command: 'git worktree add -b {{.Form.Branch}} "../$(basename $(git rev-parse --show-toplevel)).worktrees/{{.Form.Branch}}" origin/$(git symbolic-ref refs/remotes/origin/HEAD | sed "s@refs/remotes/origin/@@")'
    context: 'global'
    prompts:
      - type: 'input'
        title: 'New branch name'
        key: 'Branch'
keybinding:
  universal:
    copyToClipboard: '<c-y>'
