ui:
  showFileTree: true
  fileTreeWidth: 40
  searchTreeWidth: 50
  icons: nerd-fonts-filetype
  colorFileNames: true
  showDiffStats: false
  sideBySide: false
  hideHeader: true
  hideFooter: false
