k9s:
  cluster: arn:aws:eks:ca-central-1:876954890468:cluster/dev
  namespace:
    active: kubeflow-matt
    lockFavorites: false
    favorites:
      - argocd
      - kubeflow-vignesh
      - tailscale
      - kubeflow-matt
      - all
      - kubeflow-shahid
      - kubeflow-jay
      - niiviewer-dev
      - kubeflow-john-riskas
  view:
    active: v1/pods kubeflow-jay
  featureGates:
    nodeShell: false
  proxy: null
