# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_status_modules_right "application session date_time"

set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'o'

set-option -g mouse on

# bind C-c run "tmux save-buffer - | pbcopy"  # Copy to macOS

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
